#
# Module manifest for module 'PScription'
#
# Generated by: Tony Pitluga
#
# Generated on: 1/5/2010
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '3ebcc33f-9cdb-4f41-bd30-e5f24acf9c2c'

# Author of this module
Author = 'Tony Pitluga'

# Company or vendor of this module
CompanyName = 'None'

# Copyright statement for this module
Copyright = '(c) 2009 Anthony Pitluga'

# Description of the functionality provided by this module
Description = 'Powershell Unit Testing'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = 'Runner.ps1', 'Assertions.ps1', 'Context.ps1', 'Aggregator.ps1'

# Functions to export from this module
FunctionsToExport = 'Context' ,'Test', 'Invoke-Tests'

# Cmdlets to export from this module
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = ''

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @('Runner.ps1', 'Assertions.ps1', 'Context.ps1', 'Aggregator.ps1', 'PScription.psd1')

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}

